### ISSUE TITLE
Adds `engine` constraint

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/letsencrypt#14]
Hey, 

the module seems to depend on a specific version of nodejs (>= 0.7.6 I'd say). It'd be good to make such requirement explicit on `package.json`. 

Wdyt?

Thx!

**Comment by ipeychev** [comment]
0.7.6 no, I'm pretty sure it is not supported anymore, but maybe you meant 7.6.x? :D

Sure, Ciro, we will make this explicit, thanks! :)
