### ISSUE TITLE
Execute tests on travis

### ISSUE THREAD

**Issue by mdelapenya** [wedeploy/letsencrypt#23]

**Comment by ipeychev** [comment]
Hey @mdelapenya, what does that mean? The tests are already executing on Travis?

**Comment by mdelapenya** [comment]
Mmmm https://travis-ci.org/wedeploy/letsencrypt/jobs/308397014

You are right, I saw the `travis.yml` descriptor and seemed to me that it has no `script` phase.

I guess that travis understand the project with a recipe or something and executes it.

**Comment by mdelapenya** [comment]
Tests fixed!

![image](https://media.giphy.com/media/AvMJCeu1EMmhG/giphy.gif)
