### ISSUE TITLE
Error when trying to create a certificate for liferay.io domain

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/letsencrypt#26]
I have a project on console.wedeploy.com that I'm trying to setup a custom domain for it.

The service is `dashboard-adminliferayio.wedeploy.io` and the domain I'm trying to add is `admin.liferay.io`.

Everything seems to be looking good on the DNS configuration:

```
$ dig admin.liferay.io

; <<>> DiG 9.10.6 <<>> admin.liferay.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4808
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 2, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;admin.liferay.io.              IN      A

;; ANSWER SECTION:
admin.liferay.io.       300     IN      CNAME   dashboard-adminliferayio.wedeploy.io.
dashboard-adminliferayio.wedeploy.io. 238 IN CNAME wedeploy.com.
wedeploy.com.           32      IN      A       52.6.96.141
wedeploy.com.           32      IN      A       54.175.36.233

;; AUTHORITY SECTION:
wedeploy.com.           170234  IN      NS      jim.ns.cloudflare.com.
wedeploy.com.           170234  IN      NS      sofia.ns.cloudflare.com.

;; ADDITIONAL SECTION:
jim.ns.cloudflare.com.  83210   IN      A       173.245.59.125
jim.ns.cloudflare.com.  83210   IN      AAAA    2400:cb00:2049:1::adf5:3b7d
sofia.ns.cloudflare.com. 83210  IN      A       173.245.58.223
sofia.ns.cloudflare.com. 83210  IN      AAAA    2400:cb00:2049:1::adf5:3adf
```

But when trying to generate the certificate I'm getting the following error:

```
Error: Hostname/IP doesn't match certificate's altnames: "Host: admin.liferay.io. is not in the cert's altnames: DNS:*.wedeploy.com, DNS:wedeploy.com"
Apr 23 16:37:42.066 dashboard[0c2475bd] at Object.checkServerIdentity (tls.js:222:17)
Apr 23 16:37:42.067 dashboard[0c2475bd] at TLSSocket.&lt;anonymous> (_tls_wrap.js:1110:29)
Apr 23 16:37:42.067 dashboard[0c2475bd] at emitNone (events.js:105:13)
Apr 23 16:37:42.067 dashboard[0c2475bd] at TLSSocket.emit (events.js:207:7)
Apr 23 16:37:42.068 dashboard[0c2475bd] at TLSSocket._finishInit (_tls_wrap.js:638:8)
Apr 23 16:37:42.068 dashboard[0c2475bd] at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38)
```

@ipeychev can you investigate? It looks like everything was correctly added to PointHQ too.
@liftedkilt do you know if there's any special configuration on Let's Encrypt for that domain?

**Comment by ipeychev** [comment]
Umm, there is some miunderstanding here. The certificate has been generated successfully and not only generated, but load balancer picked it up correctly. When I try to access `dashboard-adminliferayio.wedeploy.io`, I get beautifyl greenlock, i.e., there is a valid certificate for this domain. See the screenshots below.

**It seems there is a probem with the service itself. It returns 503 even if accessed via `dashboard-adminliferayio.wedeploy.io`, i.e., without custom domain**. See the screenshots below: 

![screen shot 2018-04-24 at 11 56 01](https://user-images.githubusercontent.com/78014/39180345-ef55b720-47b6-11e8-98d9-0b632cf1e06d.png)

![screen shot 2018-04-24 at 11 57 40](https://user-images.githubusercontent.com/78014/39181206-3aecdd9c-47b9-11e8-83e9-b3e3496cf927.png)

![screen shot 2018-04-24 at 12 14 18](https://user-images.githubusercontent.com/78014/39181209-402887de-47b9-11e8-8f83-99325ff12d60.png)

**Comment by zenorocha** [comment]
Looks like it took a long time for the certificate to be generated and that led me to believe that there was a problem. The domain is working now. Thanks @ipeychev!
